development:
    url: http://core.news.geocommons.com
    finder: http://finder.news.geocommons.com
    maker: http://maker.news.geocommons.com
    scratch: file:/var/rails/core/trunk/tmp/scratch
test:
    url: http://core.test.dev.fortiusone.local
    finder: http://finder.test.dev.fortiusone.local
    maker: http://maker.test.dev.fortiusone.local
    scratch: file:/Users/semprebon/Projects/geocommons/core/tmp/scratch
production:
    url: http://core.news.geocommons.com
    finder: http://finder.news.geocommons.com
    maker: http://maker.news.geocommons.com
    scratch: file:/var/rails/core/trunk/tmp/scratch