development:
  url: http://geocommons.com
  platform_env: cloud
  scratch: file:/fortiusone/live/data/scratch
  maker: http://geocommons.com
  geocoder: http://geocoder2.geoiq.com
test:
  url: http://core.news.geocommons.com
  platform_env: cloud
  scratch: file:/fortiusone/live/data/scratch
  maker: http://maker.news.geocommons.com
  geocoder: http://geocoder2.geoiq.com
production:
  url: http://core.news.geocommons.com
  platform_env: cloud
  scratch: file:/fortiusone/live/data/scratch
  maker: http://maker.news.geocommons.com
  geocoder: http://geocoder2.geoiq.com
